### ISSUE TITLE
Honor seems to reset sporadically

### ISSUE THREAD

**Issue by sbrkopac** [E1ila/FarmLog#13]
Not sure what the root cause is but it doesn't seem to track across play sessions.

**Comment by E1ila** [comment]
What honor are you referring to, does the "Honor" row on the main log window suddenly becomes zero for current session?

**Comment by sbrkopac** [comment]
Just the tooltip seems to reset. The value in the box seems to be correct.

**Comment by E1ila** [comment]
In this case, I guess it has something to do with `todayKills` reset upon login, because `GetPVPSessionStats()` return zero. This was addressed in f72716dd27e06791a579019e989f1c31e329f6f1 by moving the `GetPVPSessionStats()` check to 5 seconds after addon got loaded.
