### ISSUE TITLE
Bonus Honor

### ISSUE THREAD

**Issue by Faldrim** [E1ila/FarmLog#17]
Bonus honor from objectives and rewards are not being added to farmlog. Only those from kills.

**Comment by E1ila** [comment]
I suspect that there's text in a format different than what's supported, so it's not parsed; can you enable debug mode `/fl debug` and copy the event text?

It should start with "OnCombatHonorEvent " and the honor event text as received by the client.

It's either this or a separate honor event the addon is not registered for.

**Comment by E1ila** [comment]
Is the missing honor comes from `_G.COMBATLOG_HONORAWARD`?

You can print it by writing `/dump _G.COMBATLOG_HONORAWARD` on your chat.

**Comment by E1ila** [comment]
I committed a fix in 1630f6ea651b1369f2672fab473de1dcf57221ad but will be able to check it at evening. Feel free to test it. :)
