### ISSUE TITLE
Lua errors since the update

### ISSUE THREAD

**Issue by Olorun** [E1ila/FarmLog#18]
First error:
2x FarmLog\FarmLog-v1.19.lua:854: attempt to index field 'farms' (a nil value)
FarmLog\FarmLog-v1.19.lua:854: in function `ResetSessionVars'
FarmLog\FarmLog-v1.19.lua:467: in function `Migrate'
FarmLog\FarmLog-v1.19.lua:2225: in function `OnAddonLoaded'
FarmLog\FarmLog-v1.19.lua:2592: in function `OnEvent'
[string "*:OnEvent"]:1: in function <[string "*:OnEvent"]:1>

Locals:
self = FarmLog {
 OnSkillsEvent = <function> defined @FarmLog\FarmLog.lua:1758
 Migrate = <function> defined @FarmLog\FarmLog.lua:438
 OnLootEvent = <function> defined @FarmLog\FarmLog.lua:2155
 OnCurrencyEvent = <function> defined @FarmLog\FarmLog.lua:1906
 OnInstanceInfoEvent = <function> defined @FarmLog\FarmLog.lua:2404
 EstimatedHonorPercent = <function> defined @FarmLog\FarmLog.lua:1649
 PurgeInstances = <function> defined @FarmLog\FarmLog.lua:784
 IncreaseBlackLotusPickStat = <function> defined @FarmLog\FarmLog.lua:2001
 debug = <function> defined @FarmLog\FarmLog.lua:269
 PrepareAuctionHouseResults = <function> defined @FarmLog\FarmLog.lua:2491
 AddonName = "FarmLog"
 ParseMinimapTooltip = <function> defined @FarmLog\FarmLog.lua:2021
 OnCombatFactionChange = <function> defined @FarmLog\FarmLog.lua:1828
 OnPlayerDead = <function> defined @FarmLog\FarmLog.lua:1727
 PauseSession = <function> defined @FarmLog\FarmLog.lua:834
 OnCombatHonorEvent = <function> defined @FarmLog\FarmLog.lua:1667
 HookTooltip = <function> defined @FarmLog\FarmLog.lua:2462
 AddInstance = <function> defined @FarmLog\FarmLog.lua:773
 ShowBlackLotusTimers = <function> defined @FarmLog\FarmLog.lua:2055
 ParseRepEvent = <function> defined @FarmLog\FarmLog.lua:1819
 ShowBlackLotusLog = <function> defined @FarmLog\FarmLog.lua:1582
 Version = "1.19.3"
 OnCombatXPEvent = <function> defined @FarmLog\FarmLog.lua:1802
 SwitchFarm = <function> defined @FarmLog\FarmLog.lua:862
 OnAuctionUpdate = <function> defined @FarmLog\FarmLog.lua:2483
 OnEnteringWorld = <function> defined @FarmLog\FarmLog.lua:2321
 OnSpellCastSuccessEvent = <function> defined @FarmLog\FarmLog.lua:1630
 GetBlackLotusItemName = <function> defined @FarmLog\FarmLog.lua:1954
 UpdateInstanceCount = <function> defined @FarmLog\FarmLog.lua:758
 GetItemValue = <function> defined @FarmLog\FarmLog.lua:2078
 CloseOpenInstances = <function> defined @FarmLog\FarmLog.lua:808
 CheckPvPDayReset = <function> defined @FarmLog\FarmLog.lua:1658
 SaveBLSeenTime = <function> defined @FarmLog\FarmLog.lua:2028
 OnPlayerLevelUp = <function> defined @FarmLog\FarmLog.lua:1734
 ResetSessionVars = <function> defined @FarmLog\FarmLog.lua:849
 DeleteFarm = <function> defined @FarmLog\FarmLog.lua:896
 InsertLoot = <function> defined @FarmLog\FarmLog.lua:2105
 Consumes = <table> {
 }
 InterfacePanel = FarmLogInterfacePanel {
 }
 UIError = <function> defined @FarmLog\FarmLog.lua:3212
 SetBlackLotusItemId = <function> defined @FarmLog\FarmLog.lua:1948
 OnUpdate = <function> defined @FarmLog\FarmLog.lua:2609
 OnSpellCastEvent = <function> defined @FarmLog\FarmLog.lua:1603
 0 = <userdata>
 LogBlackLotusCurrentLocation = <function> defined @FarmLog\FarmLog.lua:1958
 ResumeSession = <function> defined @FarmLog\FarmLog.lua:823
 AnalyzeAuctionHouseResults = <function> defined @FarmLog\FarmLog.lua:2502
 GetManualPrice = <function> defined @FarmLog\FarmLog.lua:416
 OnUpdateBattlefieldStatus = <function> defined @FarmLog\FarmLog.lua:2426
 GetCurrentSessionTime = <function> defined @FarmLog\FarmLog.lua:818
 L = <table> {
 }
 OnMoneyEvent = <function> defined @FarmLog\FarmLog.lua:1938
 ClearSession = <function> defined @FarmLog\FarmLog.lua:910
 OnCombatLogEvent = <function> defined @FarmLog\FarmLog.lua:1841
 NewSession = <funct

And another one:
2x FarmLog\FarmLog-v1.19.lua:704: attempt to index field 'farms' (a nil value)
FarmLog\FarmLog-v1.19.lua:704: in function <FarmLog\FarmLog.lua:702>
FarmLog\FarmLog-v1.19.lua:820: in function `GetCurrentSessionTime'
FarmLog\FarmLog-v1.19.lua:1105: in function `GetTitleText'
FarmLog\FarmLog-v1.19.lua:1120: in function `UpdateTitle'
FarmLog\FarmLog-v1.19.lua:844: in function `PauseSession'
FarmLog\FarmLog-v1.19.lua:2339: in function `OnEnteringWorld'
FarmLog\FarmLog-v1.19.lua:2586: in function `OnEvent'
[string "*:OnEvent"]:1: in function <[string "*:OnEvent"]:1>

Locals:
varName = "seconds"
total = false
sessionName = nil
mergeFunc = nil
name = "Winterspring"
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index field 'farms' (a nil value)"
emptySession = <function> defined @FarmLog\FarmLog.lua:204

Last one:
1x FarmLog\FarmLog-v1.19.lua:2351: attempt to index field 'farms' (a nil value)
FarmLog\FarmLog-v1.19.lua:2351: in function `OnEnteringWorld'
FarmLog\FarmLog-v1.19.lua:2586: in function `OnEvent'
[string "*:OnEvent"]:1: in function <[string "*:OnEvent"]:1>

Locals:
self = FarmLog {
 OnSkillsEvent = <function> defined @FarmLog\FarmLog.lua:1758
 Migrate = <function> defined @FarmLog\FarmLog.lua:438
 OnLootEvent = <function> defined @FarmLog\FarmLog.lua:2155
 OnCurrencyEvent = <function> defined @FarmLog\FarmLog.lua:1906
 OnInstanceInfoEvent = <function> defined @FarmLog\FarmLog.lua:2404
 EstimatedHonorPercent = <function> defined @FarmLog\FarmLog.lua:1649
 PurgeInstances = <function> defined @FarmLog\FarmLog.lua:784
 IncreaseBlackLotusPickStat = <function> defined @FarmLog\FarmLog.lua:2001
 debug = <function> defined @FarmLog\FarmLog.lua:269
 PrepareAuctionHouseResults = <function> defined @FarmLog\FarmLog.lua:2491
 AddonName = "FarmLog"
 ParseMinimapTooltip = <function> defined @FarmLog\FarmLog.lua:2021
 OnCombatFactionChange = <function> defined @FarmLog\FarmLog.lua:1828
 OnPlayerDead = <function> defined @FarmLog\FarmLog.lua:1727
 PauseSession = <function> defined @FarmLog\FarmLog.lua:834
 OnCombatHonorEvent = <function> defined @FarmLog\FarmLog.lua:1667
 HookTooltip = <function> defined @FarmLog\FarmLog.lua:2462
 AddInstance = <function> defined @FarmLog\FarmLog.lua:773
 ShowBlackLotusTimers = <function> defined @FarmLog\FarmLog.lua:2055
 ParseRepEvent = <function> defined @FarmLog\FarmLog.lua:1819
 ShowBlackLotusLog = <function> defined @FarmLog\FarmLog.lua:1582
 Version = "1.19.3"
 OnCombatXPEvent = <function> defined @FarmLog\FarmLog.lua:1802
 SwitchFarm = <function> defined @FarmLog\FarmLog.lua:862
 OnAuctionUpdate = <function> defined @FarmLog\FarmLog.lua:2483
 OnEnteringWorld = <function> defined @FarmLog\FarmLog.lua:2321
 OnSpellCastSuccessEvent = <function> defined @FarmLog\FarmLog.lua:1630
 GetBlackLotusItemName = <function> defined @FarmLog\FarmLog.lua:1954
 UpdateInstanceCount = <function> defined @FarmLog\FarmLog.lua:758
 GetItemValue = <function> defined @FarmLog\FarmLog.lua:2078
 CloseOpenInstances = <function> defined @FarmLog\FarmLog.lua:808
 CheckPvPDayReset = <function> defined @FarmLog\FarmLog.lua:1658
 SaveBLSeenTime = <function> defined @FarmLog\FarmLog.lua:2028
 OnPlayerLevelUp = <function> defined @FarmLog\FarmLog.lua:1734
 ResetSessionVars = <function> defined @FarmLog\FarmLog.lua:849
 DeleteFarm = <function> defined @FarmLog\FarmLog.lua:896
 InsertLoot = <function> defined @FarmLog\FarmLog.lua:2105
 Consumes = <table> {
 }
 InterfacePanel = FarmLogInterfacePanel {
 }
 UIError = <function> defined @FarmLog\FarmLog.lua:3212
 SetBlackLotusItemId = <function> defined @FarmLog\FarmLog.lua:1948
 OnUpdate = <function> defined @FarmLog\FarmLog.lua:2609
 OnSpellCastEvent = <function> defined @FarmLog\FarmLog.lua:1603
 0 = <userdata>
 LogBlackLotusCurrentLocation = <function> defined @FarmLog\FarmLog.lua:1958
 ResumeSession = <function> defined @FarmLog\FarmLog.lua:823
 AnalyzeAuctionHouseResults = <function> defined @FarmLog\FarmLog.lua:2502
 GetManualPrice = <function> defined @FarmLog\FarmLog.lua:416
 OnUpdateBattlefieldStatus = <function> defined @FarmLog\FarmLog.lua:2426
 GetCurrentSessionTime = <function> defined @FarmLog\FarmLog.lua:818
 L = <table> {
 }
 OnMoneyEvent = <function> defined @FarmLog\FarmLog.lua:1938
 ClearSession = <function> defined @FarmLog\FarmLog.lua:910
 OnCombatLogEvent = <function> defined @FarmLog\FarmLog.lua:1841
 NewSession = <funct

**Comment by E1ila** [comment]
I believe this is an old one that was already fixed, delete `FarmLog.lua` from `WTF/Account/ACCOUNT/REALM/CHARACTER/SavedVariables/FarmLog.lua` and it should be fine.

**Comment by E1ila** [comment]
Keep in mind that it will delete all of this character's sessions, so if you had important data gathered, you might want to fix the LUA file instead of deleting it.
