### ISSUE TITLE
Error when hovering over farmlog minimap icon won't let me do anything.

### ISSUE THREAD

**Issue by Noldat** [E1ila/FarmLog#21]
This is what i am getting

Date: 2020-01-22 10:45:23
ID: 3
Error occured in: Global
Count: 1
Message: ..\AddOns\FarmLog\FarmLog.lua line 729:
   attempt to index field 'farms' (a nil value)
Debug:
   [C]: ?
   FarmLog\FarmLog.lua:729:
      FarmLog\FarmLog.lua:728
   FarmLog\FarmLog.lua:3152: UpdateTooltipText()
   FarmLog\FarmLog.lua:3138: ShowTooltip()
   [string "*:OnEnter"]:1:
      [string "*:OnEnter"]:1
Locals:

AddOns:
  Swatter, v8.2.6377 (SwimmingSeadragon)
  TotemModFix, v0.0.10
  AccountantClassic, vv2.11.08.11302
  AdiBags, vv1.9.17-classic
  AdvancedInterfaceOptions, v1.3.3-3-g58f2fa4
  Atlas, vv1.47.00.11303.00
  AtlasClassicWoW, vv1.47.00.11303.00
  AtlasLootClassic, vv1.4.5
  AtlasLootClassicData, vv1.4.5
  AtlasLootClassicDungeonsAndRaids, vv1.4.5
  AucAdvanced, v8.2.6430 (SwimmingSeadragon)
  AucFilterBasic, v8.2.6364 (SwimmingSeadragon)
  AucScanData, v8.2.6365 (SwimmingSeadragon)
  AucStatHistogram, v8.2.6366 (SwimmingSeadragon)
  AucStatiLevel, v8.2.6370 (SwimmingSeadragon)
  AucStatPurchased, v8.2.6367 (SwimmingSeadragon)
  AucStatSimple, v8.2.6399 (SwimmingSeadragon)
  AucStatStdDev, v8.2.6369 (SwimmingSeadragon)
  AucUtilFixAH, v8.2.6371 (SwimmingSeadragon)
  Bartender4, v4.8.9-2-gc5bd6e2
  BeanCounter, v8.2.6434 (SwimmingSeadragon)
  BlackList, vv1.13.2
  ButterQuestTracker, v1.9.21
  Capping, vv4-classic
  ClassicGuildBank, v1.3
  ClassicPremade, v7.2
  DBMCore, v1.13.30-6-g4bf9a4d
  DBMDefaultSkin, v
  DBMStatusBarTimers, v
  DejaClassicStats, v1303r001
  Details, v
  DetailsTinyThreat, v
  Enchantrix, v8.2.6428 (SwimmingSeadragon)
  EnchantrixBarker, v8.2.6469 (SwimmingSeadragon)
  ExoLink, v1.0.1
  ExoLinkBIS, v1.0.1
  FarmHud, v8.3-6-classic-release
  FarmLog, vv1.19
  FishingBuddy, v0.7.3 Beta 2
  GatherMate2, v1.45.5-1-gab6216a
  HandyNotes, vv1.5.9
  honorspy, v1.7.1
  InFlightLoad, v1.13.005
  Informant, v8.2.6374 (SwimmingSeadragon)
  ItemRack, v
  KuiMedia, v
  KuiNameplates, v
  KuiNameplatesCore, v
  LeatrixMaps, v1.13.45.alpha.1
  LeatrixPlus, v1.13.46.alpha.2
  LFG113, v
  Misspelled, v1.7.7
  MoveAnything, v17.1.0
  OmniCC, v8.3.1
  OPie, vAncient Walnut 5
  PerlArcaneBar, v
  PerlCombatDisplay, v
  PerlConfig, v
  PerlFocus, v
  PerlParty, v
  PerlPartyPet, v
  PerlPartyTarget, v
  PerlPlayer, v
  PerlPlayerPet, v
  PerlTarget, v
  PerlTargetTarget, v
  Prat30, v3.7.47
  Prat30Libraries, v
  Quartz, v3.5-classic-5
  Questie, v5.5.1
  QuestLogExperience, v11302.07-Classic
  Rank14LosSAClassic, v2.0.0
  RealMobHealth, v2.18
  ServerFriendsOnly, v1.1.14
  SlideBar, v8.2.6375 (SwimmingSeadragon)
  Spy, v1.0.21
  Stubby, v8.2.6376 (SwimmingSeadragon)
  TitanClassic, v1.1.5.11303
  TitanClassicAmmo, v1.1.5.11303
  TitanClassicBag, v1.1.5.11303
  TitanClassicClock, v1.1.5.11303
  TitanClassicGold, v1.1.5.11303
  TitanClassicGuild, v1.0.0.3
  TitanClassicLocation, v1.1.5.11303
  TitanClassicLootType, v1.1.5.11303
  TitanClassicPerformance, v1.1.5.11303
  TitanClassicRegen, v1.1.5.11303
  TitanClassicRepair, v1.1.5.11303
  TitanClassicVolume, v1.1.5.11303
  TitanClassicXP, v1.1.5.11303
  TomTom, vv11303-1.0.9
  TownsfolkTracker, v1.0.7
  TradeSkillMaster, vv4.9.17
  TradeSkillMasterAppHelper, vv4.0.7
  VuhDo, v3.111-classic
  VuhDoOptions, v3.111-classic
  WeakAuras, v2.16.1-4-ge6439ac
  WhatsTraining, v1.8.7
  WhereToGatherClassic, v1.0
  WideQuestLog, v
  WideQuestLogLevels, v
  BlizRuntimeLib_enUS v1.13.3.11303 <none>
  (ck=baa)

**Comment by E1ila** [comment]
This is a result of an old bug, corrupting `REALM/CHAR/SavedVariables/FarmLog.lua` file. Delete it and it'll be resolved.
