### ISSUE TITLE
Support multiple accounts

### ISSUE THREAD

**Issue by madamsmall** [E1ila/FarmLog#22]
Multiple accounts should be able to use the addon. Currently only a single account can use it correctly, the rest are non-responsive.

**Comment by madamsmall** [comment]
Was a bug -- fixed by reinstall

**Comment by E1ila** [comment]
Multiple accounts are support, each char should have a separate log.

You may have chars with old SavedVariables/FarmLog.lua that's causing it to get stuck, try to delete it.
