### ISSUE TITLE
Russian fonts issue

### ISSUE THREAD

**Issue by E1core** [E1ila/FarmLog#34]
Name of loot in Russian is displayed incorrectly.
How can I resolve this issue?
<img width="177" alt="fonts issue" src="https://user-images.githubusercontent.com/71591467/93710090-896e1280-fb4c-11ea-8c9f-83d30bdf164b.png">

**Comment by E1core** [comment]
I resolved this issue.
You need to edit file FarmLog.lua and to replace line 5 from **local FONT_NAME = "Fonts\\FRIZQT__.TTF"** to **local FONT_NAME = "Fonts\\FRIZQT__CYR.TTF"**

File FarmLog.lua has direction \World of Warcraft\_classic_\Interface\AddOns\FarmLog
<img width="471" alt="farmlog" src="https://user-images.githubusercontent.com/71591467/93713957-12df0e00-fb68-11ea-9798-ead85d865191.png">

**Comment by Airimee** [comment]
Additionally you need to edit file FarmLogOptions.lua line 55  from **local FONT = "Fonts\FRIZQT__.TTF" to local FONT = "Fonts\FRIZQT__CYR.TTF"**

![FarmLogOptions](https://user-images.githubusercontent.com/77284143/104196033-65547b00-5434-11eb-8c90-6b7de02b1554.jpg)

**Comment by ko0f** [comment]
Although FRIZQT___CYR is available on western clients, it doesn't support special European characters e.g. é, ï, ö
Due to this, we cannot use it as a replacement for FRIZQT__.TTF

I'll try to see how this can be properly fixed.
