### ISSUE TITLE
Allow renaming a farm session from UI

### ISSUE THREAD

**Issue by EvelynSays** [E1ila/FarmLog#6]
I have been unable to find a way to rename sessions. This would be an incredibly useful feature, as it would be great to be able to keep track of the gph in different farm spots in the overworld.

For example I would like to know the difference between farming on satyrs, or farming in plaguelands.

Thanks.

**Comment by E1ila** [comment]
You can rename a session using command `/fl ren NEWNAME`. I'll add a UI option for that later on.
