### ISSUE TITLE
Error after logging

### ISSUE THREAD

**Issue by Ogaitdrood** [E1ila/FarmLog#8]
Message: Interface\AddOns\FarmLog\FarmLog.lua:656: attempt to index field 'farms' (a nil value)

Time: Wed Nov 13 21:37:32 2019

Count: 1

Stack: Interface\AddOns\FarmLog\FarmLog.lua:656: attempt to index field 'farms' (a nil value)

Interface\AddOns\FarmLog\FarmLog.lua:656: in function `ResetSessionVars'

Interface\AddOns\FarmLog\FarmLog.lua:354: in function `Migrate'

Interface\AddOns\FarmLog\FarmLog.lua:1763: in function `OnAddonLoaded'

Interface\AddOns\FarmLog\FarmLog.lua:2029: in function `OnEvent'

[string "*:OnEvent"]:1: in function <[string "*:OnEvent"]:1>

Locals: self = FarmLog {

OnSkillsEvent = <function> defined @Interface\AddOns\FarmLog\FarmLog.lua:1351

NewSession = <function> defined @Interface\AddOns\FarmLog\FarmLog.lua:721

OnCombatLogEvent = <function> defined @Interface\AddOns\FarmLog\FarmLog.lua:1427

OnCurrencyEvent = <function> defined @Interface\AddOns\FarmLog\FarmLog.lua:1494

OnInstanceInfoEvent = <function> defined @Interface\AddOns\FarmLog\FarmLog.lua:1891

OnEnteringWorld = <function> defined @Interface\AddOns\FarmLog\FarmLog.lua:1845

GetBlackLotusItemName = <function> defined @Interface\AddOns\FarmLog\FarmLog.lua:1540

PurgeInstances = <function> defined @Interface\AddOns\FarmLog\FarmLog.lua:587

UpdateInstanceCount = <function> defined @Interface\AddOns\FarmLog\FarmLog.lua:561

CloseOpenInstances = <function> defined @Interface\AddOns\FarmLog\FarmLog.lua:611

IncreaseBlackLotusPickStat = <function> defined @Interface\AddOns\FarmLog\FarmLog.lua:1587

AskQuestion = <function> defined @Interface\AddOns\FarmLog\FarmLog.lua:753

GetLastInstance = <function> defined @Interface\AddOns\FarmLog\FarmLog.lua:597

OnSpellCastEvent = <function> defined @Interface\AddOns\FarmLog\FarmLog.lua:1297

ResetSessionVars = <function> defined @Interface\AddOns\FarmLog\FarmLog.lua:651

DeleteFarm = <function> defined @Interface\AddOns\FarmLog\FarmLog.lua:694

PrepareAuctionHouseResults = <function> defined @Interface\AddOns\FarmLog\FarmLog.lua:1933

UIError = <function> defined @Interface\AddOns\FarmLog\FarmLog.lua:2386

ParseCSV = <function> defined @Interface\AddOns\FarmLog\FarmLog.lua:1283

InsertLoot = <function> defined @Interface\AddOns\FarmLog\FarmLog.lua:1638

OnUpdate = <function> defined @Interface\AddOns\FarmLog\FarmLog.lua:2046

OnCombatFactionChange = <function> defined @Interface\AddOns\FarmLog\FarmLog.lua:1416

OnEvent = <function> defined @Interface\AddOns\FarmLog\FarmLog.lua:1993

OnLootEvent = <function> defined @Interface\AddOns\FarmLog\FarmLog.lua:1691

OnPlayerDead = <function> defined @Interface\AddOns\FarmLog\FarmLog.lua:1330

OnLootOpened = <function> defined @Interface\AddOns\FarmLog\FarmLog.lua:1451

OnAuctionUpdate = <function> defined @Interface\AddOns\FarmLog\FarmLog.lua:1925

PauseSession = <function> defined @Interface\AddOns\FarmLog\FarmLog.lua:637

Migrate = <function> defined @Interface\AddOns\FarmLog\FarmLog.lua:329

OnEnterCombat = <function> defined @Interface\AddOns\FarmLog\FarmLog.lua:1902

OnAddonLoaded = <function> defined @Interface\AddOns\FarmLog\FarmLog.lua:1758

AnalyzeAuctionHouseResults = <function> defined @Interface\AddOns\FarmLog\FarmLog.lua:1944

OnCombatHonorEvent = <function> defined @Interface\AddOns\FarmLog\FarmLog.lua:1326

0 = <userdata>

GetCurrentSessionTime = <function> defined @Interface\AddOns\FarmLog\FarmLog.lua:621

ParseSkillEvent = <function> defined @Interface\AddOns\FarmLog\FarmLog.lua:1342

OnMoneyEvent = <function> defined @Interface\AddOns\FarmLog\FarmLog.lua:1526

ClearSession = <function> defined @Interface\AddOns\FarmLog\FarmLog.lua:708

ParseMinimapTooltip = <function> defined @Interface\AddOns\FarmLog\FarmLog.lua:1607

AddInstance = <function> defined @Interface\AddOns\FarmLog\FarmLog.lua:576

SetBlackLotusItemId = <function> defined @Interface\AddOns\FarmLog\FarmLog.lua:1534

ParseXPEvent = <function> defined @Interface\AddOns\FarmLog\FarmLog.lua:1378

LogBlackLotusCurrentLocation = <function> defined @Interface\AddOns\FarmLog\FarmLog.lua:1544

LogBl

**Comment by E1ila** [comment]
Fixed in 555f3ff
